### ISSUE TITLE
Autogenerate platform-specific wrapper classes and jars 

### ISSUE THREAD

**Issue by shardulm94** [linkedin/transport#10]
Currently, when authoring a UDF, a user first extends one of the StdUDF_i abstract classes and defines the business logic of the UDF. However, after the core logic of the UDF is written, the user has to create _n_ different modules accompanying the core UDF module (one for each platform) [Hive|Presto|Spark]. Through these modules, the user is exposed to platform-specific details such as the UDF API, testing methodology, set of dependencies and the packaging requirements. If we look at the contents of these modules though, we see that the wrappers and gradle files a user has to write consists of mostly boilerplate code. However writing these modules is where the user tends to spend most of his time. This makes them a great candidate to be auto-generated.

This task will be split into a few subtasks:
- [x] An annotation processor to extract metadata about Transport UDFs defined by the user - #11 
- [x] A Gradle task to generate wrappers classes from the metadata - #15 
- [x] A Gradle task to compile generated wrappers and package them into JARs - #18 
- [x] A Gradle plugin to automatically apply Transport related gradle tasks and configurations - #17
